backend:
  name: github
  repo: AbsoluteDestiny/luminous # Path to your Github repository
  branch: lumsvids # Branch to update
publish_mode: editorial_workflow
media_folder: "src/assets/images"
public_folder: "/images"
display_url: https://lumsvids.com
collections:
  - name: "vids" # Used in routes, e.g., /admin/collections/blog
    label: "Vids" # Used in the UI
    folder: "src/vids" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{vid_id}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Vid ID (e.g. 132 or m23)", name: "vid_id", widget: "string", required: true, default: "abcd"}
      - {label: "Vid Title", name: "title", widget: "string", required: true}
      - {label: "Vid Creation Date (UTC)", name: "date", widget: "datetime", required: true}
      - {label: "Fandoms (separate multiple with a comma)", name: "fandoms", widget: "list", required: false}
      - {label: "Vidders", name: "creators", widget: "string", default: "Luminosity", required: true}
      - {label: "Song Title", name: "song", widget: "string", required: true}
      - {label: "Song Artist", name: "artist", widget: "string", required: true}
      - {label: "Vid Description", name: "body", widget: "markdown", required: false}
      - {label: "mp4 filename", name: "mp4name", widget: "string", required: false}
      - {label: "mp4 size", name: "mp4size", widget: "string", required: false}
      - {label: "mp4 width", name: "width", widget: "number", required: false}
      - {label: "mp4 height", name: "height", widget: "number", required: false}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Barcode", name: "barcode", widget: "image", required: false}
  - name: "data" # Used in routes, e.g., /admin/collections/blog
    label: "Site Configuration" # Used in the UI
    folder: "src/data" # The path to the folder where the documents are stored
    create: false # Allow users to create new documents in this collection
    slug: "config" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Site Title", name: "title", widget: "string", required: true}
      - {label: "Site Description", name: "description", widget: "string", required: true}
      - {label: "Site Author", name: "author", widget: "string", default: "Luminosity Deville", required: true}
      - {label: "URL", name: "url", widget: "string", required: true}
      - {label: "Vid File CDN", name: "vid_cdn", widget: "string", required: true}
      - {label: "Facebook App ID", name: "fb_appid", widget: "string", required: true}
      - {label: "Twitter Handle", name: "twitter_handle", widget: "string", required: true}
